export const ACTIVITY_LIST_REQUEST = "ACTIVITY_LIST_REQUEST";
export const ACTIVITY_LIST_SUCCESS = "ACTIVITY_LIST_SUCCESS";
export const ACTIVITY_LIST_FAIL = "ACTIVITY_LIST_FAIL";

export const ACTIVITY_ADD_REQUEST = "ACTIVITY_ADD_REQUEST";
export const ACTIVITY_ADD_SUCCESS = "ACTIVITY_ADD_SUCCESS";
export const ACTIVITY_ADD_FAIL = "ACTIVITY_ADD_FAIL";

export const ACTIVITY_EDIT_REQUEST = "ACTIVITY_EDIT_REQUEST";
export const ACTIVITY_EDIT_SUCCESS = "ACTIVITY_EDIT_SUCCESS";
export const ACTIVITY_EDIT_FAIL = "ACTIVITY_EDIT_FAIL";

export const ACTIVITY_DELETE_REQUEST = "ACTIVITY_DELETE_REQUEST";
export const ACTIVITY_DELETE_SUCCESS = "ACTIVITY_DELETE_SUCCESS";
export const ACTIVITY_DELETE_FAIL = "ACTIVITY_DELETE_FAIL";

export const ACTIVITY_ADD_DEVICE_REQUEST = "ACTIVITY_ADD_REQUEST";
export const ACTIVITY_ADD_DEVICE_SUCCESS = "ACTIVITY_ADD_SUCCESS";
export const ACTIVITY_ADD_DEVICE_FAIL = "ACTIVITY_ADD_FAIL";
export const ACTIVITY_ADD_DEVICE = "ACTIVITY_ADD_DEVICE";
