export const DATE_LIST_REQUEST = "DATE_LIST_REQUEST";
export const DATE_LIST_SUCCESS = "DATE_LIST_SUCCESS";
export const DATE_LIST_FAIL = "DATE_LIST_FAIL";

export const DATE_DETAILS_REQUEST = "DATE_DETAILS_REQUEST";
export const DATE_DETAILS_SUCCESS = "DATE_DETAILS_SUCCESS";
export const DATE_DETAILS_FAIL = "DATE_DETAILS_FAIL";
