export const DEVICE_LIST_REQUEST = "DEVICE_LIST_REQUEST";
export const DEVICE_LIST_SUCCESS = "DEVICE_LIST_SUCCESS";
export const DEVICE_LIST_FAIL = "DEVICE_LIST_FAIL";

export const DEVICE_DETAILS_REQUEST = "DEVICE_DETAILS_REQUEST";
export const DEVICE_DETAILS_SUCCESS = "DEVICE_DETAILS_SUCCESS";
export const DEVICE_DETAILS_FAIL = "DEVICE_DETAILS_FAIL";

export const DEVICE_DELETE_REQUEST = "DEVICE_DELETE_REQUEST";
export const DEVICE_DELETE_SUCCESS = "DEVICE_DELETE_SUCCESS";
export const DEVICE_DELETE_FAIL = "DEVICE_DELETE_FAIL";

export const DEVICE_ADD_REQUEST = "DEVICE_ADD_REQUEST";
export const DEVICE_ADD_SUCCESS = "DEVICE_ADD_SUCCESS";
export const DEVICE_ADD_FAIL = "DEVICE_ADD_FAIL";

export const DEVICE_UPDATE_REQUEST = "DEVICE_UPDATE_REQUEST";
export const DEVICE_UPDATE_SUCCESS = "DEVICE_UPDATE_SUCCESS";
export const DEVICE_UPDATE_FAIL = "DEVICE_UPDATE_FAIL";
