export const USER_LOGIN_REQUEST = "USER_LOGIN REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIn_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_LIST_REQUEST = "USER_LIST REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
